version: "3.7"
services:
  database:
    image: postgres:9.6
    container_name: full_db_postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    depends_on:
      - database
    ports:
      - '8080:8080'
volumes:
  data: